# Generated by Django 5.2.7 on 2025-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_company', models.CharField(max_length=70)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('locality_address', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.AutoField(primary_key=True, serialize=False)),
                ('depature_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('regularity_time', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'race',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route_stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
            ],
            options={
                'db_table': 'route_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('locality', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('house_number', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('place_number', models.IntegerField()),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=45)),
                ('place_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'vehicle_employee',
                'managed': False,
            },
        ),
    ]
